### ISSUE TITLE
client issues when accepting clients in uyunis.

### ISSUE THREAD

**Issue by curinos2023** [sbluhm/uyuni#129]
# Question
i installed and have it running venv-salt-minions on 3 clients, seems like if i accespt one client and either removes the other  and add the new client with the hostname of the old client. there is no relations whatsover among clients, but from the master it gets mixed up.
any help will be greatly appreciated.

 [salt.crypt       :847 ][ERROR   ][168654] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate

**Comment by sbluhm** [comment]
Hey, did you maybe clone the clients from each other?
Maybe check `/etc/venv-salt-minion/minion_id` that they are unique.

Delete all minions from the server, drop all keys https://server.example.com/rhn/manager/systems/keys and restart from scratch.

What is the version you are testing this on? Did you test it on any other version or even the upstream SUSE Leap Release?

**Comment by curinos2023** [comment]
minion_id are unique.
keys are dc-dlb01, dc-dtableau03, all keys different from the master. saly-key -F but then i restarted venv-salt-minion service in dc-lb01 and hostname shows as dc-dtableau03, it is happening same thing with another one. it is just a fresh installation for uyuni in rocky 9.  Uyuni release [2024.01](https://dc-patch01.novantas.com/docs/en/release-notes/release-notes-server.html)

**Comment by sbluhm** [comment]
could it be a DNS resolution issue?
I would have to check with a new install later this week.
BTW, 2024.03 is available already in case you want to update.
Maybe also ask at the official Uyuni forum over at https://github.com/uyuni-project/uyuni/issues

**Comment by curinos2023** [comment]
no it is not a dns issue. Have u seen any problems when installing uyunis in rocky 9.
client is acting up and dropping the registration with the master server.

**Comment by sbluhm** [comment]
Haven't noticed it on my instance. But that one has been updated since a few yrs. So would have to test it on a vanilla system.

**Comment by curinos2023** [comment]
i updated spacewalk to the latest same issue.
salts is able to see the 4 clients, but only one goes to systems. and one of the clients has a wrong system name but the correct minion_id

**Comment by curinos2023** [comment]
rockylinux 9 bootstrap repository not found, using RES9 bootstrap repository instead
https://dc-patch01.novantas.com/pub/repositories/res/9/bootstrap/repodata/repomd.xml:
2024-03-12 15:32:57 ERROR 404: 404.
Bootstrap repo 'https://dc-patch01.novantas.com/pub/repositories/res/9/bootstrap' does not exist.
 adding 'module_hotfixes' flag to the repository config
venv-salt-minion-3006.0-24.11.uyuni.x86_64
  no packages missing.
Warning: failed loading '/etc/yum.repos.d/susemanager:bootstrap.repo', skipping.
Last metadata expiration check: 1:11:36 ago on Tue 12 Mar 2024 02:21:22 PM EDT.
Dependencies resolved.
Nothing to do.
Complete!
i am not using products because i am not using enterprise, i am using my own channels.
it not loading '/etc/yum.repos.d/susemanager:bootstrap.repo', skipping. to the client.

**Comment by sbluhm** [comment]
Can you check what is on the server at `/var/www/html/pub/repositories...` ?
I am actually not sure where it comes from. My clients do not use that repository.

How are you installing the software on the client?
I usually do an `dnf install  https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/x86_64/venv-salt-minion.rpm` and then configure the file `/etc/venv-salt-minion/minion.d/susemanager.conf`

I think it is best to ask upstream on this as I am actually not that experienced in the intended way of adding clients or configuring Uyuni. For me it just works and I just stick to it.

**Comment by curinos2023** [comment]
i wanted to ruled out if any issues with salt and using ssh bootstrapping, but the issue persists, there are 2 different clients but uyuni sees it as the same one. it just renames it. any idea here
2024-03-13 06:13:33,092 [ajp-nio-127.0.0.1-8009-exec-8] ERROR com.redhat.rhn.frontend.action.common.DownloadFile - Error parsing file download url: /_vti_inf.html
2024-03-13 06:14:00,015 [ajp-nio-127.0.0.1-8009-exec-10] WARN  com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction - Minion 'dc-dtableau03.novantas.com' already registered, updating profile to 'dc-dlb01' [bcab8c57099b4afaaac385027d0de7f7]

**Comment by curinos2023** [comment]
here is a similar issue i found but i dont find any fix.
I cannot bootstrap one more clients that created from the same template(image)
First, i create multiple VMs from the same template image, there is no problem to bootstrap one VM client. after that other VM clients
will not be listed at system list even though the WEB UI says i have bootstrap successfully.

**Comment by sbluhm** [comment]
Hello @curinos2023 , are you still having issues? I noticed lumarel's reply in the chat:

> the salt-minion uses the machine-id as identifier 👍️ (to recreate just delete /etc/machine-id and run systemd-machine-id-setup
