### ISSUE TITLE
Missing dependency installing uyuni

### ISSUE THREAD

**Issue by sipvoip** [sbluhm/uyuni#30]
Error: 
 Problem: package spacewalk-postgresql-4.2.1-5.1.noarch requires spacewalk-common = 4.2.1-5.1, but none of the providers can be installed
  - package patterns-uyuni_server-2021.02-5.2.x86_64 requires spacewalk-postgresql, but none of the providers can be installed
  - package spacewalk-common-4.2.1-5.1.noarch requires subscription-matcher, but none of the providers can be installed
  - conflicting requests
  - nothing provides mvn(com.thoughtworks.xstream:xstream) = 1.4.15 needed by subscription-matcher-0.26-5.6.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by alxm8** [comment]
I have same issue on centos stream

**Comment by sbluhm** [comment]
Try again now. I have fixed up all packages.

**Comment by sbluhm** [comment]
@sipvoip / @alxm8  am closing this ticket as installation works again. Please re-open if required.
