### ISSUE TITLE
Missing Package spacewalk-client-tools

### ISSUE THREAD

**Issue by Q-Storm** [sbluhm/uyuni#33]
Hello @sbluhm ,

Thanks for you work and all the effort to run Uyuni on Centos/Alma/Rocky Linux.
I'm still running Spacewalk and thought I give it a try to install Uyuni on Rocky. 

It seems like on of you repos is missing a dependency package

# dnf -y install patterns-uyuni_server 
 Last metadata expiration check: 1:04:20 ago on Mon 12 Jul 2021 11:48:10 AM CEST.
Error: 
 Problem: package spacewalk-utils-4.3.0-5.1.noarch requires spacewalk-certs-tools, but none of the providers can be installed
  - package patterns-uyuni_server-2021.07-6.1.x86_64 requires spacewalk-utils, but none of the providers can be installed
  - package spacewalk-certs-tools-4.3.0-3.1.noarch requires spacewalk-client-tools, but none of the providers can be installed
  - conflicting requests
  - package spacewalk-client-tools-4.3.0-5.2.noarch is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

The repository only provides a src package. 
Am I missing a step or a doing?

**Comment by sbluhm** [comment]
Let me check again. I just installed it on Friday.

**Comment by sbluhm** [comment]
Before/whilst I am checking, did you disable the spacewalk modules? Spacewalk and Uyuni packages do not run at the same time.

`dnf -y module disable rhn-tools satellite-5-client # Don't use Spacewalk packages.`

**Comment by Q-Storm** [comment]
yes, I kickstarted the system with my old Spacewalk which installed rhn-client.
After I disabled the modules I needed to remove the rhn-client,rhncfg,python3-rhncfg-client,python3-rhncfg,python3-spacewalk-usix from my system in order to install Uyuni.
Thank you for the support and keep up the good work.

**Comment by sbluhm** [comment]
:) Fell into the same trap and took me some time to figure out.
