### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.12 - mgr-create-bootstrap-repo creates repo in wrong directory

### ISSUE THREAD

**Issue by lumarel** [sbluhm/uyuni#52]
While setting up the first repos I noticed that the bootstrap repos are missing.
But they actually aren't missing, they were just created in the wrong directory.

In my case with RL 8 it looked like that in the creation log:
```bash
# mgr-create-bootstrap-repo -c rockylinux-8-x86_64-uyuni

Creating bootstrap repo for rockylinux-8-x86_64-uyuni
copy 'redhat-rpm-config-125-1.el8.noarch'
copy 'salt-3002.2-27.1.uyuni.x86_64'
copy 'salt-minion-3002.2-27.1.uyuni.x86_64'
copy 'python3-salt-3002.2-27.1.uyuni.x86_64'
copy 'python3-babel-2.5.1-7.el8.noarch'
copy 'python3-msgpack-0.4.6-2.4.uyuni.x86_64'
copy 'python3-tornado-4.2.1-2.4.uyuni.x86_64'
copy 'python3-zmq-17.0.0-5.5.uyuni.x86_64'
copy 'python3-jinja2-2.10.1-3.el8.noarch'
copy 'python3-m2crypto-0.35.2-2.4.uyuni.x86_64'
copy 'python3-markupsafe-0.23-19.el8.x86_64'
copy 'python3-psutil-5.4.3-11.el8.x86_64'
copy 'python3-pyyaml-3.12-12.el8.x86_64'
copy 'python3-requests-2.20.0-2.1.el8_1.noarch'
copy 'openpgm-5.2.122-17.4.uyuni.x86_64'
copy 'zeromq-4.1.6-12.4.uyuni.x86_64'
copy 'python3-urllib3-1.24.2-5.el8.noarch'
copy 'python3-idna-2.5-5.el8.noarch'
copy 'python3-chardet-3.0.4-7.el8.noarch'
copy 'python3-pysocks-1.6.8-3.el8.noarch'
copy 'python3-pytz-2017.2-9.el8.noarch'
copy 'python3-setuptools-39.2.0-6.el8.noarch'
copy 'python3-distro-1.4.0-2.module+el8.3.0+120+426d8baf.noarch'
copy 'dmidecode-3.2-10.el8:1.x86_64'
Directory walk started
Directory walk done - 24 packages
Temporary output repo path: /srv/www/htdocs/pub/repositories/rockylinux/8/bootstrap.tmp/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
ERROR: package 'venv-salt-minion' not found

Suggestions:
mgr-create-bootstrap-repo uses the locally synchronized versions of files
from the Tools repository, and uses the locally synchronized pool channel
for dependency resolution.
Both should be fully synced before running the mgr-create-bootstrap-repo script.
```

That made it clear where it put it.
So the issue is that the values for the bootstrap repo destinations in the `/usr/share/susemanager/mgr_bootstrap_data.py` are wrong.

**Comment by sbluhm** [comment]
Also the OS detection in line 526 of bootstrap.sh needs to be adapted.

@lumarel note on your `ERROR: package 'venv-salt-minion' not found` that you need to update your repo.. Script is master and the public Uyuni repo WAS still behind.

**Comment by lumarel** [comment]
Yep, I did add the Development repo then and there it was already available, but now the same package is also available in the normal repo 👌🏻

But that's not what I was talking about in this issue :)

**Comment by lumarel** [comment]
It's about that right now the `mgr_bootstrap_data.py` file has the location for `/srv/www/htdocs/pub/repositories/` in it for every distribution, that file would need a different content for the EL 8 platforms

**Comment by sbluhm** [comment]
sed -i 's#/srv/www/htdocs#/var/www/html#' /usr/share/susemanager/mgr_bootstrap_data.py
does the trick.

**Comment by sbluhm** [comment]
https://github.com/uyuni-project/uyuni/pull/4607/files
