### ISSUE TITLE
Bootstrapping does not work

### ISSUE THREAD

**Issue by sbluhm** [sbluhm/uyuni#53]
Bootstrapping a salt client does not work or not reliably.
Systems --> Bootstrap

Destination: minimal install AlmaLinux 8 Client

**Comment by lumarel** [comment]
To me it looks like it completely finishes the salt-master part, but never initiates the ssh session to the client, to install and configure the salt-minion.

**Comment by sbluhm** [comment]
Works pretty well on CentOS 7. Might have been a NS infrastructure issue.
To be tested again on EL8.

**Comment by sbluhm** [comment]
Also works on EL8. So blaming it on network config issues. Closing but keeping an eye on it.
