### ISSUE TITLE
What repositories are actually required? - Uyuni

### ISSUE THREAD

**Issue by abotelho-cbn** [sbluhm/uyuni#69]
# Question
_What repositories are actually required?_

I came from here: https://www.bluhm-de.com/content/os-tools/en/applications/uyuni/installing-uyuni-on-centos-8.html

I'm trying to test this out on AlmaLinux, and going through the steps manually. But it seems like the /Other/AlmaLinux_8/ and /Other:/EL/AlmaLinux_8/ repositories aren't available, and then installing patterns-uyuni_server (after installing the rpm at https://raw.githubusercontent.com/sbluhm/uyuni-repo/master/new-packages.txt) spits out the following:

[root@testuyuni yum.repos.d]# dnf -y install patterns-uyuni_server
Last metadata expiration check: 0:05:17 ago on Wed 16 Feb 2022 12:53:16 PM EST.
Error: 
 Problem: package patterns-uyuni_server-2022.02-1.1.uyuni1.x86_64 requires susemanager, but none of the providers can be installed
  - conflicting requests
  - nothing provides openslp-server needed by susemanager-4.3.8-1.2.uyuni1.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

Is this expected?
Cheers

**Comment by sbluhm** [comment]
@abotelho-cbn , thank you very much for your interest in this project!
It seems you missed the first step in the instructions (or the variable wasn't in memory anymore):
`REPO_SOURCE=https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master`
So the full REPO URLS are
```
dnf -y config-manager --add-repo https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master/AlmaLinux_8/
dnf -y config-manager --add-repo https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/Other/AlmaLinux_8/
```
Note that I am currently having issues on AlmaLinux that the webservice doesn't start. Others are not having this issue so might just be my machine. Can you let me know if this all works for you?

**Comment by abotelho-cbn** [comment]
I'll give a try again. Maybe I misstyped the URLs.

Absolutely! I'll give you as much feedback as possible.

Having this run on RHEL-based distros would be wonderful. We need a proper alternative to Foreman on EL.
Cheers

**Comment by abotelho-cbn** [comment]
> @abotelho-cbn , thank you very much for your interest in this project! It seems you missed the first step in the instructions (or the variable wasn't in memory anymore): `REPO_SOURCE=https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master` So the full REPO URLS are
> 
> ```
> dnf -y config-manager --add-repo https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master/AlmaLinux_8/
> dnf -y config-manager --add-repo https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/Other/AlmaLinux_8/
> dnf -y config-manager --add-repo https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/Other:/EL/AlmaLinux_8/
> ```
> 
> Note that I am currently having issues on AlmaLinux that the webservice doesn't start. Others are not having this issue so might just be my machine. Can you let me know if this all works for you?

Should the mgr-setup -s step be outputting how I access the web GUI? Official documentation only refers to Yast, which is making it tricky to determine what services need starting.

**Comment by sbluhm** [comment]
there are two possible ways. On my website, it mentions this line in the code:
`# curl https://raw.githubusercontent.com/sbluhm/uyuni-repo/master/root/setup_env.sh > /root/setup_env.sh # Optional to load default values. Otherise wizard is run.`
Uncomment it and run. It will create the file `/root/setup_env.sh`. Modify it for your needs. The basic file is sufficient for (my) testing.
The other option would be to just run `mgr-setup -s` without downloading the file. `mgr-setup`reads that file for all values. It will ask you for all missing parameters (which would be all, if you don't have the file).

Yast does some additional checks like free space, enough memory before writing the file `/root/setup_env.sh`. My aim is to also include these checks into `mgr-setup` one day. But as this is a test setup or even one time only setup, I think a non-fancy way should really be sufficient.

Once `mgr-setup` completes, you can access your instance via `https://<servername>`. It will ask you to set up the first user.
This should have been shown also by `mgr-setup` near the end before starting the services.
